---
title: "imitation"
output: html_document
date: "2023-12-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(udpipe)
```

```{r read-data}
ldp <- read_csv(here("data/ldp_full_utts_1mill.csv"))
adj_utts <- read_csv(here("data/ldp_conc_adj_noun_utts_with_session.csv"))

ldp_adjs <- ldp %>%
  left_join(adj_utts, by = c("id" = "doc_id", "subject", "session", "person", "chat", "utts")) %>%
  arrange(id)

ldp_lag_pairs <- ldp_adjs %>%
  select(utt_id, subject, session, chat, adj_token, noun_token) %>%
  mutate(adj_noun_phrase = paste(adj_token, noun_token)) %>%
  paste.data.frame(term = "adj_noun_phrase", 
                   group = c("utt_id", "subject", "session", "chat"), collapse = " ") %>%
  mutate(adj_noun_phrase = trimws(str_remove_all(adj_noun_phrase, "NA")),
         adj_noun_phrase = str_replace_all(adj_noun_phrase, "  ", " "),
         adj_noun_phrase = str_replace_all(adj_noun_phrase, "  ", " ")) %>%
  group_by(subject, session) %>%
  mutate(lag_data = paste(lag(adj_noun_phrase), lag(adj_noun_phrase, 2), lag(adj_noun_phrase, 3),
                          lag(adj_noun_phrase, 4), lag(adj_noun_phrase, 5))) %>%
  ungroup() %>%
  mutate(lag_data = trimws(str_remove_all(lag_data, "NA")),
         lag_data = str_replace_all(lag_data, "  ", " "),
         lag_data = str_replace_all(lag_data, "  ", " ")) 
   
ldp_adjs_rep <- ldp_adjs %>%
  left_join(ldp_lag_pairs %>% select(-adj_noun_phrase), by = c("utt_id", "subject", "session", "chat"))
```


```{r}
ldp_child_non_rep <- ldp_adjs_rep %>%
  filter(person == "child", !is.na(adj_token), !is.na(noun_token)) %>%
  mutate(adj_noun_phrase = paste(adj_token, noun_token)) %>%
  filter(!str_detect(lag_data, adj_noun_phrase))

ldp_child_all <- ldp_adjs_rep %>%
  filter(person == "child", !is.na(adj_token), !is.na(noun_token)) %>%
  mutate(adj_noun_phrase = paste(adj_token, noun_token))

```