---
title: "data_processing"
author: "Claire Bergey"
date: "12/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(feather)
library(data.table)
library(tidytext)
library(tidyverse)
library(ggridges)
library(scales)
library(ggthemes)
library(lme4)
library(lmerTest)
library(broom.mixed)
```

```{r read-data}
coded_data <- read_csv(here("data/ldp_cabnc_data.csv"))
```

```{r}
all_subjs <- coded_data %>%
  count(subid)

keep_subjs <- coded_data %>%
  filter(is.na(adjective) & is.na(noun) & rating == 5)

subj_data <- coded_data %>%
  filter(!(is.na(adjective) & is.na(noun))) %>%
  filter(subid %in% keep_subjs$subid) 

nonsense_pairs <- subj_data %>%
  group_by(adjective, noun) %>%
  tally(rating == 8) %>%
  filter(n >= 2) %>%
  mutate(adj_noun_phrase = paste(adjective, noun, sep = " "))

subj_data <- subj_data %>%
  mutate(adj_noun_phrase = paste(adjective, noun, sep = " ")) %>%
  filter(!(adj_noun_phrase %in% nonsense_pairs$adj_noun_phrase),
         rating != 8)

mean_ratings <- subj_data %>%
  group_by(adjective, noun) %>%
  summarise(mean_typ = mean(rating))
```

```{r}
ldp <- read_csv(here("data/ldp_conc_adj_noun_utts_with_session.csv"))
orig_tokens <- read_csv(here("data/ldp_cabnc_pairs_all_info.csv"))

ldp <- ldp %>%
  left_join(orig_tokens, by = c("adj_token" = "adj", "noun_token" = "noun_orig")) %>%
  rename(adjective = adj_token) %>%
  select(doc_id, sentence, noun_token, adjective, noun, prenominal, 
         dataset, subject, session, person, chat, utts, mass, adj_article, 
         article, adj_token_id, noun_token_id) 

ldp_coded <- ldp %>%
  mutate(age = (4*session + 10)) %>%
  left_join(mean_ratings, by = c("adjective", "noun")) %>%
  rename(mean_rating = mean_typ) %>%
  filter(!is.na(mean_rating))
```

```{r read-cabnc}
cabnc <- read_csv(here("data/all_cabnc_ldpParentandKid_conc_unique_UTTS.csv"))

# for now this has both cabnc and ldp utterances. let's get a list of most common adjectives to use ...
common_adjs <- cabnc %>%
  left_join(orig_tokens, by = c("adj_token" = "adj", "noun_token" = "noun_orig")) %>%
  rename(adjective = adj_token) %>%
  count(adjective) %>%
  arrange(desc(n)) %>%
  slice(1:500)

common_adjs_250 <- cabnc %>%
  left_join(orig_tokens, by = c("adj_token" = "adj", "noun_token" = "noun_orig")) %>%
  rename(adjective = adj_token) %>%
  count(adjective) %>%
  arrange(desc(n)) %>%
  slice(1:250)

#write_csv(common_adjs_250, here("data/250_common_adjs.csv"))

cabnc <- cabnc %>%
  filter(dataset == "cabnc_utts_udpipe") %>%
  left_join(orig_tokens, by = c("adj_token" = "adj", "noun_token" = "noun_orig")) %>%
  rename(adjective = adj_token) %>%
  select(doc_id, sentence, noun_token, adjective, noun, prenominal, 
         dataset, mass, adj_article, 
         article, adj_token_id, noun_token_id) %>%
  left_join(mean_ratings, by = c("adjective", "noun")) %>%
  rename(mean_rating = mean_typ) %>%
  filter(!is.na(mean_rating))
```

```{r}
all_pairs <- subj_data %>%
  distinct(adjective, noun)

#write_csv(all_pairs, here("data/final_pairs_ldp_cabnc.csv"))

# then we run that file through word2vec/get_wiki_similarities.py to get this file ...
w2v_judgments <- read_csv(here("data/all_judgments_ldp_cabnc.csv")) %>%
  mutate(ldp_similarity = if_else(ldp_similarity == "nan", NA_character_, ldp_similarity),
         wiki_similarity = as.numeric(wiki_similarity),
         ldp_similarity = as.numeric(ldp_similarity))

# and run through bert_gpt/get_GPT.py to get GPT-2 probabilities...
gpt2_judgments <- read_csv(here("data/gpt2_judgments_ldp_cabnc.csv"))
```

```{r}
min_max_ratings <- mean_ratings %>%
  group_by(noun) %>%
  mutate(min_typ = min(mean_typ), max_typ = max(mean_typ)) %>%
  distinct(noun, min_typ, max_typ) %>%
  filter(min_typ != max_typ, max_typ >= 5, min_typ <= 3) 

high_low_pairs <- mean_ratings %>%
  filter(noun %in% min_max_ratings$noun) %>%
  left_join(min_max_ratings, by = c("noun")) %>%
  filter(mean_typ == min_typ | mean_typ == max_typ) %>%
  select(adjective, noun, mean_typ) %>%
  group_by(noun) %>%
  arrange(noun, desc(mean_typ)) 

weighted_ratings <- subj_data %>%
  group_by(adjective, noun) %>%
  count(rating) %>%
  mutate(p = n/sum(n)) %>%
  ungroup()  %>%
  group_by(rating) %>%
  summarise(p = sum(p)) %>%
  ungroup() %>%
  mutate(p = p/sum(p))
```

```{r}
mean_ratings %>%
  ggplot(aes(x = mean_typ)) +
  geom_density() +
  scale_x_continuous(minor_breaks = seq(1 , 7, 1), breaks = seq(1, 7, 1), labels = c('never', 'rarely', 'sometimes', 'about half', 'often', 'almost always', 'always'))

weighted_ratings %>%
  ggplot(aes(x = rating, y = p)) +
  geom_bar(stat = "identity") +
  scale_x_continuous(minor_breaks = seq(1 , 7, 1), breaks = seq(1, 7, 1), labels = c('never', 'rarely', 'sometimes', 'about half', 'often', 'almost always', 'always'))
```

```{r}
w2v_judgments %>%
  ggplot(aes(x = turker_judgment, y = wiki_similarity)) +
  geom_point(alpha = 0.2) + 
  geom_smooth()

w2v_judgments %>%
  ggplot(aes(x = turker_judgment, y = ldp_similarity)) +
  geom_point(alpha = 0.2) + 
  geom_smooth()
```

```{r}
gpt2_judgments %>% mutate(logprob = log(prob)) %>% filter(logprob < -20) %>% View()
                          
gpt2_judgments %>%
  ggplot(aes(x = mean, y = log(prob))) +
  geom_point(alpha = 0.2) + 
  geom_smooth()
```


```{r}
ldp_parent_plot <- ldp_coded %>%
  filter(person == "parent") %>%
  mutate(typicality=mean_rating) %>%
  group_by(session) %>%
  mutate(age = min(age)) %>%
  ggplot(aes(x = typicality, y=age, group=age, fill=age)) +
  geom_density_ridges2() +
  ylab("Child Age (months)") +
  xlab("More Atypical                   More Typical \n Typicality of adjective-noun pairs") +
  geom_vline(xintercept = 4, size=1, linetype="solid")+
  scale_fill_gradient(low="cornsilk", high=muted("red")) +
  theme_few() +
  theme(#panel.grid = element_line(color="lightgrey",size=0.5), 
    axis.line = element_line(colour = "black"),
    axis.ticks = element_line(),
    axis.text.x = element_text(size=11, angle=28, hjust=1),
    axis.text.y = element_text(size=11),
    legend.position = "none") +
  scale_x_continuous(minor_breaks = seq(1 , 7, 1), breaks = seq(1, 7, 1), labels = c('never', 'rarely', 'sometimes', 'about half', 'often', 'almost always', 'always')) +
  scale_y_continuous(minor_breaks = seq(14, 58, 4), breaks = seq(14, 58, 4)) +
  theme(
    strip.background =element_rect(fill="transparent"),
    panel.background = element_rect(fill = "transparent"), # bg of the panel
    plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
    panel.grid.major = element_blank(), # get rid of major grid
    panel.grid.minor = element_blank(), # get rid of minor grid
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
    legend.box.background = element_rect(fill = "transparent"), # get rid of legend panel bg
    legend.key = element_rect(fill = "transparent", colour = NA), # get rid of key legend fill, and of the surrounding
    axis.line = element_line(colour = "black") # adding a black line for x and y axis
)

ggsave(ldp_parent_plot, filename = "writing/journal_article/ldp_parent_plot.png",  width = 6, height = 8, units = "in", dpi = 300, bg = "transparent")
```


```{r}
ldp_child_plot <- ldp_coded %>%
  filter(person == "child") %>%
  mutate(typicality=mean_rating) %>%
  group_by(session) %>%
  mutate(age = min(age)) %>%
  ggplot(aes(x = typicality, y=age, group=age, fill=age)) +
  geom_density_ridges2() +
  ylab("Child Age (months)") +
  xlab("More Atypical                   More Typical \n Typicality of adjective-noun pairs") +
  geom_vline(xintercept = 4, size=1, linetype="solid")+
  scale_fill_gradient(low="cornsilk", high=muted("red")) +
  theme_few() +
  theme(#panel.grid = element_line(color="lightgrey",size=0.5), 
    axis.line = element_line(colour = "black"),
    axis.ticks = element_line(),
    axis.text.x = element_text(size=11, angle=28, hjust=1),
    axis.text.y = element_text(size=11),
    legend.position = "none") +
  scale_x_continuous(minor_breaks = seq(1 , 7, 1), breaks = seq(1, 7, 1), labels = c('never', 'rarely', 'sometimes', 'about half', 'often', 'almost always', 'always')) +
  scale_y_continuous(minor_breaks = seq(14, 58, 4), breaks = seq(14, 58, 4)) +
  theme(
    strip.background =element_rect(fill="transparent"),
    panel.background = element_rect(fill = "transparent"), # bg of the panel
    plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
    panel.grid.major = element_blank(), # get rid of major grid
    panel.grid.minor = element_blank(), # get rid of minor grid
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
    legend.box.background = element_rect(fill = "transparent"), # get rid of legend panel bg
    legend.key = element_rect(fill = "transparent", colour = NA), # get rid of key legend fill, and of the surrounding
    axis.line = element_line(colour = "black") # adding a black line for x and y axis
)

ggsave(ldp_child_plot, filename = "writing/journal_article/ldp_child_plot.png",  width = 6, height = 8, units = "in", dpi = 300, bg = "transparent")
```

```{r cabnc}
cabnc_plot <- cabnc %>%
  mutate(typicality=mean_rating) %>%
  ggplot(aes(x = typicality)) +
  geom_density(fill="cornsilk") +
  xlab("More Atypical                   More Typical \n Typicality of adjective-noun pairs") +
  geom_vline(xintercept = 4, size=1, linetype="solid")+
  theme_few() +
  theme(#panel.grid = element_line(color="lightgrey",size=0.5), 
    axis.line = element_line(colour = "black"),
    axis.ticks = element_line(),
    axis.text.x = element_text(size=11, angle=28, hjust=1),
    axis.text.y = element_text(size=11),
    legend.position = "none") +
  scale_x_continuous(minor_breaks = seq(1 , 7, 1), breaks = seq(1, 7, 1), labels = c('never', 'rarely', 'sometimes', 'about half', 'often', 'almost always', 'always')) +
  scale_y_continuous(minor_breaks = seq(14, 58, 4), breaks = seq(14, 58, 4)) +
  theme(
    strip.background =element_rect(fill="transparent"),
    panel.background = element_rect(fill = "transparent"), # bg of the panel
    plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
    panel.grid.major = element_blank(), # get rid of major grid
    panel.grid.minor = element_blank(), # get rid of minor grid
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
    legend.box.background = element_rect(fill = "transparent"), # get rid of legend panel bg
    legend.key = element_rect(fill = "transparent", colour = NA), # get rid of key legend fill, and of the surrounding
    axis.line = element_line(colour = "black") # adding a black line for x and y axis
)

ggsave(cabnc_plot, filename = "writing/journal_article/cabnc_plot.png",  width = 6, height = 3, units = "in", dpi = 300, bg = "transparent")
```

```{r}
parent_typical_ratings <- ldp_coded %>%
  filter(person == "parent") %>%
  group_by(age, adjective, noun, mean_rating) %>%
  count() %>%
  ungroup() %>%
  mutate(typical = mean_rating >= 5)

typicals_parent <- ldp_coded %>%
  filter(person == "parent") %>%
  group_by(age, adjective, noun, mean_rating) %>%
  count() %>%
  ungroup() %>%
  mutate(typical = mean_rating >= 5) %>%
  group_by(age, typical) %>%
  summarise(weighted_sum = sum(n), sum = n()) %>%
  pivot_longer(cols = c(sum, weighted_sum), names_to = "measure", values_to = "sum") %>%
  group_by(age, measure) %>%
  mutate(prop = sum / sum(sum)) %>%
  filter(typical)

cabnc_typicals <- cabnc %>%
  group_by(adjective, noun, mean_rating) %>%
  count() %>%
  ungroup() %>%
  mutate(typical = mean_rating >= 5) %>%
  group_by(typical) %>%
  summarise(weighted_sum = sum(n), sum = n()) %>%
  pivot_longer(cols = c(sum, weighted_sum), names_to = "measure", values_to = "sum") %>%
  group_by(measure) %>%
  mutate(prop = sum / sum(sum)) %>%
  filter(typical) %>%
  mutate(corpus = "Adult-Adult Speech")

typical_type_lmer <- glmer(typical ~ log(age) + (1|noun), 
                      data = parent_typical_ratings, 
     family = "binomial") %>% 
  tidy() %>%
  filter(effect == "fixed")

typical_token_lmer <- glmer(typical ~ log(age) + (1|noun), 
                      data = parent_typical_ratings, 
                      weights = n,
     family = "binomial") %>% 
  tidy() %>%
  filter(effect == "fixed")
```

```{r typicals-plot}
parent_typicals_plot <- typicals_parent %>% 
  filter(measure == "weighted_sum") %>% 
  ggplot(aes(x = age,y = prop, colour = age)) +
  geom_smooth(method = "glm", formula = y~x,
                      method.args = list(family = gaussian(link = 'log')),color = "black") +
  geom_point(aes(fill=age), colour="black",pch=21, size=5) +
  ylab("Proportion of modifiers rated as \n typical of modified noun") +
  xlab("Child's Age (months)") +
  scale_x_continuous(minor_breaks = seq(14, 58, 4), breaks = seq(14, 58, 4))+
  scale_fill_gradient(low="cornsilk", high=muted("red")) +
  theme(#axis.line = element_line(colour = "black"),
        #axis.ticks = element_line(),
        #axis.text = element_text(size=14),
        #panel.grid = element_line(color="lightgrey",size=0.5),
        #axis.text.x = element_text(size=10, angle=15),
        legend.position = "none",
        aspect.ratio = 1/1.62) +
  theme(
    strip.background =element_rect(fill="transparent"),
    panel.background = element_rect(fill = "transparent"), # bg of the panel
    plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
    panel.grid.major = element_blank(), # get rid of major grid
    panel.grid.minor = element_blank(), # get rid of minor grid
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
    legend.box.background = element_rect(fill = "transparent"), # get rid of legend panel bg
    legend.key = element_rect(fill = "transparent", colour = NA), # get rid of key legend fill, and of the surrounding
    axis.line = element_line(colour = "black") # adding a black line for x and y axis
)

ggsave(parent_typicals_plot, filename = "writing/journal_article/parent_typicals_plot.png",  width = 6, height = 4, units = "in", dpi = 300, bg = "transparent")

cabnc_typicals_plot <- cabnc_typicals %>%
  filter(measure == "weighted_sum") %>% 
  ggplot(aes(x = corpus,y = prop, colour = age)) +
  geom_point(colour="black",pch=21, size=5) +
  scale_y_continuous(limits = c(0, 0.125)) +
  scale_fill_gradient(low="cornsilk", high=muted("red")) +
  theme(#axis.line = element_line(colour = "black"),
        #axis.ticks = element_line(),
        #axis.text = element_text(size=14),
        #panel.grid = element_line(color="lightgrey",size=0.5),
        #axis.text.x = element_text(size=10, angle=15),
        legend.position = "none",
        aspect.ratio = 1/1.62) +
  theme(
    strip.background =element_rect(fill="transparent"),
    panel.background = element_rect(fill = "transparent"), # bg of the panel
    plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
    panel.grid.major = element_blank(), # get rid of major grid
    panel.grid.minor = element_blank(), # get rid of minor grid
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
    legend.box.background = element_rect(fill = "transparent"), # get rid of legend panel bg
    legend.key = element_rect(fill = "transparent", colour = NA), # get rid of key legend fill, and of the surrounding
    axis.line = element_line(colour = "black") # adding a black line for x and y axis
)

ggsave(cabnc_typicals_plot, filename = "writing/journal_article/cabnc_typicals_plot.png",  width = 2, height = 8, units = "in", dpi = 300, bg = "transparent")

```

```{r}
ldp_parent_overall_plot <- ldp_coded %>%
  filter(person == "parent") %>%
  mutate(typicality=mean_rating) %>%
  ggplot(aes(x = typicality)) +
  geom_density(fill="cornsilk") +
  xlab("More Atypical                   More Typical \n Typicality of adjective-noun pairs") +
  geom_vline(xintercept = 4, size=1, linetype="solid")+
  theme_few() +
  theme(#panel.grid = element_line(color="lightgrey",size=0.5), 
    axis.line = element_line(colour = "black"),
    axis.ticks = element_line(),
    axis.text.x = element_text(size=11, angle=28, hjust=1),
    axis.text.y = element_text(size=11),
    legend.position = "none") +
  scale_x_continuous(minor_breaks = seq(1 , 7, 1), breaks = seq(1, 7, 1), labels = c('never', 'rarely', 'sometimes', 'about half', 'often', 'almost always', 'always')) +
  scale_y_continuous(minor_breaks = seq(14, 58, 4), breaks = seq(14, 58, 4)) +
  theme(
    strip.background =element_rect(fill="transparent"),
    panel.background = element_rect(fill = "transparent"), # bg of the panel
    plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
    panel.grid.major = element_blank(), # get rid of major grid
    panel.grid.minor = element_blank(), # get rid of minor grid
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
    legend.box.background = element_rect(fill = "transparent"), # get rid of legend panel bg
    legend.key = element_rect(fill = "transparent", colour = NA), # get rid of key legend fill, and of the surrounding
    axis.line = element_line(colour = "black") # adding a black line for x and y axis
)

ggsave(ldp_parent_overall_plot, filename = "writing/journal_article/ldp_parent_overall_plot.png",  width = 6, height = 3, units = "in", dpi = 300, bg = "transparent")

```